spring:
  datasource:
    username: root
    password: root
#    url: jdbc:mysql://192.168.1.108:3306/mall_pms
    url: jdbc:mysql://100.66.167.136:3306/mall_pms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: mall-product

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  #sql映射文件位置
  global-config:
    db-config:
      id-type: auto       #自增主键
      logic-delete-value: 0
      logic-not-delete-value: 1

server:
  port: 10001
logging:
  level: 
    com.wyjie.mall: debug
    